### stats
GET http://localhost:8080/api/zkb/stats/
Accept: application/json

### test 1
GET http://localhost:8080/api/zkb/v1/stuff/
Accept: application/json

### test 2
GET http://localhost:8080/api/zkb/v1/stuff?test=a
Accept: application/json

### test 3 - 404
GET http://localhost:8080/api/zkb/v1/
Accept: application/json

### test 4 - 404
GET http://localhost:8080/api/zkb/v1/
Accept: application/json

### pass through
GET http://localhost:8080/api/zkb/v1/kills/regionID/10000003/
Accept: application/json

### pass through 2
GET http://localhost:8080/api/zkb/v1/losses/solo/
Accept: application/json

### pass through 3
GET http://localhost:8080/api/zkb/v1/w-space/corporationID/98076299/page/4/
Accept: application/json